version: 0.0
os: linux

files:
  - source: /Website/index.html
    destination: /var/www/html
  - source: /Website/style.css
    destination: /var/www/html
  - source: /images
    destination: /var/www/html

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  # NEW: This hook runs after ApplicationStart to test the deployment
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root